# Generated by Django 5.1.1 on 2024-09-23 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('arrival_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
